version: '3'
services: 
    hugo:
        image: klakegg/hugo
        volumes:
            - ".:/src"
        entrypoint: sh
        ports:
            - "1313:1313"
        tty: true
        working_dir: /src
